offset_lookup = {
    "filler_1": 0,
    "filler_2": 1,
    "filler_3": -1,
    "house": 0,
    "pavilion":0,
    "lake": -3,
    "pagoda": 0,
    "river": -3,
    "stone_formation_1": -1,
    "stone_formation_2": -1,
    "stone_formation_3": -1,
    "stone_formation_4": -1,
    "stone_horizontal_1_ratio_rule": -1,
    "stone_horizontal_2_ratio_rule": -1,
    "stone_horizontal_3_ratio_rule": -1,
    "stone_vertical_1_ratio_rule": -1,
    "stone_vertical_2_ratio_rule": -1,
    "tori": 0,
    "tree_green_1": 0,
    "tree_green_2": 0,
    "tree_pink_1": 0,
    "tree_pink_2": 0,
    "waterfall": -1,
}
