offset_lookup = {
    "Filler 1": 0,
    "Filler 2": 1,
    "Filler 3": -1,
    "House": 0,
    "Pavillion":0,
    "Lake": -4,
    "Pagoda": 0,
    "River": -3,
    "Stone Formation 1": -1,
    "Stone Formation 2": -1,
    "Stone Formation 3": -1,
    "Stone Formation 4": -1,
    "Stone Horizontal 1 Ratio Rule": -1,
    "Stone Horizontal 2 Ratio Rule": -1,
    "Stone Horizontal 3 Ratio Rule": -1,
    "Stone Vertical 1 Ratio Rule": -1,
    "Stone Vertical 2 Ratio Rule": -1,
    "Tori": 0,
    "Tree Green 1": 0,
    "Tree Green 2": 0,
    "Tree Pink 1": 0,
    "Tree Pink 2": 0,
    "Waterfall": -1,
}
